apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: geojson-hpa 
spec: 
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: geojson-processor
  minReplicas: 1
  maxReplicas: 5 
  metrics:
    - type: Resource 
      resource:
        name: cpu 
        targetPort: 
          type: Utilization 
          averageUtilization: 60 
            
